name: deploy github page using vuepress
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUNDLE_DIST: ${{ secrets.BUNDLE_DIST }}

jobs:
  prepare:
    name: prepare_environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build project
        run: yarn && yarn build --dest $BUNDLE_DIST
      - name: deploy github page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: $BUNDLE_DIST