name: deploy github page using vuepress
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUNDLE_DIST: ${{ secrets.BUNDLE_DIST }}

jobs:
  depoly:
    name: deploy github page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install pnpm
        run: yarn global add pnpm
      - name: build project
        run: pnpm install && pnpm build --dest $BUNDLE_DIST
      - run: ls
      - name: deploy github page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ${{ env.BUNDLE_DIST }}